import time

input("Start with Enter this Program...")
print("true")
time.sleep(0.1)
print("Program is loading...")
time.sleep(3)
print("intialiasing data files...")
time.sleep(1)
print("Game started=true")
time.sleep(1)
print("------------------------------")
time.sleep(0.1)
print("---------Adverbialsätze-------")
time.sleep(0.1)
print("------------------------------")
time.sleep(1)
print("|-language=German/Deutsch")
time.sleep(0.5)
print("Erstelle deinen Character:")
time.sleep(0.5)
people_name = input("Name:  ")
people_surname = input("Nachname:  ")
people_age = input("Alter:  ")
time.sleep(1)
print("Character wird erstellt...")
time.sleep(3)
print("Characterauswahl:")
time.sleep(0.1)
print(":::::Character1:::::")
time.sleep(0.5)
print(people_name)
time.sleep(0.5)
print(people_surname)
time.sleep(0.5)
print(people_age)
input("Möchtest du :::::1::::: auswählen?_")
input(":::::1::::: wurde akzeptiert weiter?")
time.sleep(1)
print("------------------------------")
time.sleep(0.1)
print("---------Adverbialsätze-------")
time.sleep(0.1)
print("------------------------------")
time.sleep(1)
print("Wählen Sie Ihren Modus aus, tippen Sie jeweils die Taste für:")
print(":::::1:::::_Adverbialsätze bestimmen")
print(":::::2:::::_Fragen von Adverbialsätze")
print(":::::3:::::_Beispiel von Fragen")
Modusauswahl = int(input("Eingabe:  "))
if Modusauswahl == 1:
    print("Zur Auswahl steht:")
    print("Adverbialsätze:")
    print("[8727]Temporalsatz")
    print("[2678]Lokalsatz")
    print("[5289]Modalsatz")
    print("[2584]Konditionalsatz")
    print("[9156]Kausalsatz")
    print("[8351]Finalsatz")
    print("[4921]Konzessivsatz")
    time.sleep(1)
    EP = 0
    time.sleep(0.1)
    question_1 = int(input("Aufgabe1:Nenne mir den Adverbialsatz [der Zeit]:  "))
    if question_1 == 8727:
        print("das ist richtig!:)")
        print("Der Temporalsatz ist ein Adverbialsatz der Zeit.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_1 > 8727:
        print("das ist falsch!:(")
        print("Der Temporalsatz ist ein Adverbialsatz der Zeit.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_1 < 8727:
        print("das ist falsch!:(")
        print("Der Temporalsatz ist ein Adverbialsatz der Zeit.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_2 = int(input("Aufgabe2:Nenne mir den Adverbialsatz [des Grundes]:  "))
    if question_2 == 9156:
        print("das ist richtig!:)")
        print("Der Kausalsatz ist ein Adverbialsatz des Grundes.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_2 > 9156:
        print("das war falsch!:(")
        print("Der Kausalsatz ist ein Adverbialsatz des Grundes.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_2 < 9156:
        print("das war falsch!:(")
        print("Der Kausalsatz ist ein Adverbialsatz des Grundes.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_3 = int(input("Aufgabe3:Nenne mir den Adverbialsatz [des Zwecks]:  "))
    if question_3 == 8351:
        print("das ist richtig!:)")
        print("Der Finalsatz ist ein Adverbialsatz des Zwecks.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_3 > 8351:
        print("das war falsch!:(")
        print("Der Finalsatz ist ein Adverbialsatz des Zwecks.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_3 < 8351:
        print("das war falsch!:(")
        print("Der Finalsatz ist ein Adverbialsatz des Zwecks.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_4 = int(input("Aufgabe4:Nenne mir den Adverbialsatz [der Art und Weise]:  "))
    if question_4 == 5289:
        print("das war richtig!:)")
        print("Der Modalsatz ist ein Adverbialsatz der Art und Weise.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_4 > 5289:
        print("das war falsch!:(")
        print("Der Modalsatz ist ein Adverbialsatz der Art und Weise.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_4 < 5289:
        print("das war falsch!:(")
        print("Der Modalsatz ist ein Adverbialsatz der Art und Weise.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_5 = int(input("Aufgabe5:nenne mir den Adverbialsatz [der Bedingung]"))
    if question_5 == 2584:
        print("das war richtig!:)")
        print("Der Konditionalsatz ist ein Adverbialsatz der Bedingung.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_5 > 2584:
        print("das war falsch!:(")
        print("Der Konditionalsatz ist ein Adverbialsatz der Bedingung.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_5 < 2584:
        print("das war falsch!:(")
        print("Der Konditionalsatz ist ein Adverbialsatz der Bedingung.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_6 = int(input("Aufgabe6:nenne mir den Adverbialsatz [des Ortes]"))
    if question_6 == 2678:
        print("das war richtig!:)")
        print("Der Lokalsatz ist ein Adverbialsatz des Ortes.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_6 > 2678:
        print("das war falsch!:(")
        print("Der Lokalsatz ist ein Adverbialsatz des Ortes.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_6 < 2678:
        print("das war falsch!:(")
        print("Der Lokalsatz ist ein Adverbialsatz des Ortes.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    question_7 = int(input("Aufgabe7:Nenne mir den Adverbialsatz [der Einschränkung]"))
    if question_7 == 4921:
        print("das war richtig!:)")
        print("Der Konzessivsatz ist ein Adverbialsatz der Einschränkung.")
        print("[+150EP]")
        EP = (EP + 150)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_7 > 4921:
        print("das war falsch!:(")
        print("Der Konzessivsatz ist ein Adverbialsatz der Einschränkung.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
    if question_7 < 4921:
        print("das war falsch!:(")
        print("Der Konzessivsatz ist ein Adverbialsatz der Einschränkung.")
        print("[-50EP]")
        EP = (EP - 50)
        print("Dein EP-Gehalt beträgt EP", EP)
input("Betätigen Sie eine beliebige Taste, um das Spiel zu verlassen...")